theme: minima
title: This is my first page using the GitHub Pages
author: Samuel
email: samuel@dusek.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first page using the GitHub Pages. I am trying to learn more about Git and GitHub.

# social links
twitter_username: _samu3l # DO NOT include the @ character, or else the build will fail!
github_username:  samueldusek # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
